### ISSUE TITLE
"KeyError:1614" was reported when using [contrast_polygenicity.py] to make the plot among five traits. 

### ISSUE THREAD

**Issue by siqi2401** [huwenboshi/hess#19]
"KeyError:1614" was reported when using [contrast_polygenicity.py] to make the plot among five traits. 
【code】
python ./hess/misc/contrast_polygenicity.py \
--local-hsqg-est trait1.txt trait2.txt trait3.txt trait4.txt trait5.txt \
--show-se --no-negative --trait-names trait1 trait2 trait3 trait4 trait5 \
--out .five_traits_contrast.pdf
【Error】
Traceback (most recent call last):
  File "./hess0.5/misc/contrast_polygenicity.py", line 146, in <module>
    main()
  File "./hess0.5/misc/contrast_polygenicity.py", line 77, in main
    total_hsq_jk = all_total_hsq[i]-all_local_hsq_sorted[i][k]
  File "/lustre/home/acct-clsjj/clsjj/.local/lib/python2.7/site-packages/pandas/core/series.py", line 868, in __getitem__
    result = self.index.get_value(self, key)
  File "/home/../python2.7/site-packages/pandas/core/indexes/base.py", line 4375, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/_libs/index.pyx", line 81, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 89, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 987, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 993, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 1614

**Comment by siqi2401** [comment]
I have no idea why this error emerged and how to solve it. [contrast_polygenicity.py] works when I create the contrast polygenicity plot between 2 traits.
