### ISSUE TITLE
IndexError: list index out of range for local rg

### ISSUE THREAD

**Issue by nenduru1** [huwenboshi/hess#20]
Hi, 
for some chromosomes i ma getting the below error for local rg. please provide your input.

[INFO] 204309 SNPs read from reference panel
[INFO] Loaded 286860 SNPs with rs IDs and single-letter alleles on chromosome 19 from the GWAS summary data file
[INFO] 160989 SNPs left after filtering
Traceback (most recent call last):
  File "/data2/nenduru/software/hess-0.5.4-beta/hess-0.5.4-beta/hess.py", line 217, in <module>
    main()
  File "/data2/nenduru/software/hess-0.5.4-beta/hess-0.5.4-beta/hess.py", line 45, in main
    argmap['out'])
  File "/data2/nenduru/software/hess-0.5.4-beta/hess-0.5.4-beta/src/estimation.py", line 391, in local_rhog_step1
    sumstats2 = SumStats(sumstats_fnm[1], chrom)
  File "/data2/nenduru/software/hess-0.5.4-beta/hess-0.5.4-beta/src/sumstats.py", line 113, in __init__
    idx = idx_map[name]; val = cols[idx]
IndexError: list index out of range

thanks,
Nitesh

**Comment by DongshengWu** [comment]
Hello, can you provide some guidance on addressing this issue? I've encountered the same question as well.

**Comment by Zhangzzzzzy** [comment]
> Hello, can you provide some guidance on addressing this issue? I've encountered the same question as well.

Have you found a solution yet? I have the same problem.

**Comment by Zhangzzzzzy** [comment]
> Hi, for some chromosomes i ma getting the below error for local rg. please provide your input.
> 
> [INFO] 204309 SNPs read from reference panel [INFO] Loaded 286860 SNPs with rs IDs and single-letter alleles on chromosome 19 from the GWAS summary data file [INFO] 160989 SNPs left after filtering Traceback (most recent call last): File "/data2/nenduru/software/hess-0.5.4-beta/hess-0.5.4-beta/hess.py", line 217, in main() File "/data2/nenduru/software/hess-0.5.4-beta/hess-0.5.4-beta/hess.py", line 45, in main argmap['out']) File "/data2/nenduru/software/hess-0.5.4-beta/hess-0.5.4-beta/src/estimation.py", line 391, in local_rhog_step1 sumstats2 = SumStats(sumstats_fnm[1], chrom) File "/data2/nenduru/software/hess-0.5.4-beta/hess-0.5.4-beta/src/sumstats.py", line 113, in **init** idx = idx_map[name]; val = cols[idx] IndexError: list index out of range
> 
> thanks, Nitesh

Have you found a solution yet? I have the same problem.

**Comment by Zhangzzzzzy** [comment]
> Have you found a solution yet? I have the same problem.

Have you found a solution yet? I have the same problem.

**Comment by Zhangzzzzzy** [comment]
> Hi, for some chromosomes i ma getting the below error for local rg. please provide your input.
> 
> [INFO] 204309 SNPs read from reference panel [INFO] Loaded 286860 SNPs with rs IDs and single-letter alleles on chromosome 19 from the GWAS summary data file [INFO] 160989 SNPs left after filtering Traceback (most recent call last): File "/data2/nenduru/software/hess-0.5.4-beta/hess-0.5.4-beta/hess.py", line 217, in main() File "/data2/nenduru/software/hess-0.5.4-beta/hess-0.5.4-beta/hess.py", line 45, in main argmap['out']) File "/data2/nenduru/software/hess-0.5.4-beta/hess-0.5.4-beta/src/estimation.py", line 391, in local_rhog_step1 sumstats2 = SumStats(sumstats_fnm[1], chrom) File "/data2/nenduru/software/hess-0.5.4-beta/hess-0.5.4-beta/src/sumstats.py", line 113, in **init** idx = idx_map[name]; val = cols[idx] IndexError: list index out of range
> 
> thanks, Nitesh

Have you found a solution yet? I have the same problem.
