### ISSUE TITLE
I cannot module load refpanl

### ISSUE THREAD

**Issue by harryyiheyang** [huwenboshi/hess#23]
I faced a problem in installing this package:
Traceback (most recent call last):
  File "hess.py", line 8, in <module>
    from src.estimation import *
  File "/home/yxy1234/hess_env/src/estimation.py", line 6, in <module>
    from refpanel import *
ModuleNotFoundError: No module named 'refpanel'
Could you tell me where I can install the pacakge refpanel?
Thank you.

**Comment by zhuxxyy12** [comment]
I met the same problem. Do you know how to solve it now?
