### ISSUE TITLE
step1 KeyError: 'ID" 

### ISSUE THREAD

**Issue by AEAEAESSC** [huwenboshi/hess#31]
[INFO] @----------------------------------------------------------@
       |         HESS       |      v0.5      |    9/October/2017  |
       |----------------------------------------------------------|
       |  (C) 2017 Huwenbo Shi, GNU General Public License, v3    |
       |----------------------------------------------------------|
       |  For documentation, citation & bug-report instructions:  |
       |   http://bogdan.bioinformatics.ucla.edu/software/hess/   |
       @----------------------------------------------------------@
[INFO] Command started at: Thu, 07 Dec 2023 09:05:39
[INFO] Command issued:
    hess.py \
        --bfile /home/zhanya/hess-hess-0.5/1kg_eur_1pct/1kg_eur_1pct_chr22 \
        --local-rhog /external/zhanya/hess/mdd3.txt /external/zhanya/hess/whr4.txt \
        --partition /home/zhanya/hess-hess-0.5/fourier_ls-all.bed \
        --out /external/zhanya/hess/step1 \
        --chrom 22
/home/zhanya/hess-hess-0.5/src/refpanel.py:13: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  partition = pd.read_table(filename, delim_whitespace=True)
[INFO] Loaded 24 partitions on chromosome 22
[INFO] Average window size is 1466370
/home/zhanya/hess-hess-0.5/src/refpanel.py:61: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  names=['SNP', 'BP', 'A0', 'A1'])
[INFO] 123295 SNPs read from reference panel
[INFO] Loaded 132836 SNPs with rs IDs and single-letter alleles on chromosome 22 from the GWAS summary data file
Traceback (most recent call last):
  File "hess.py", line 217, in <module>
    main()
  File "hess.py", line 45, in main
    argmap['out'])
  File "/home/zhanya/hess-hess-0.5/src/estimation.py", line 390, in local_rhog_step1
    sumstats1.filter_sumstats(refpanel.get_map())
  File "/home/zhanya/hess-hess-0.5/src/sumstats.py", line 168, in filter_sumstats
    elif a1a0 in reverse[a1a2]: flip.append(i)
KeyError: 'ID"
This code only encountered a problem in the 22nd loop, reporting a KeyError: 'ID'. I used the same code to run 21 chromosomes before, and I don't know where the problem occurred
here is my code：
for chrom in $(seq 22)
do
    python hess.py \
--local-rhog /external/zhanya/hess/mdd3.txt /external/zhanya/hess/whr4.txt \
--chrom $chrom \
--bfile /home/zhanya/hess-hess-0.5/1kg_eur_1pct/1kg_eur_1pct_chr$chrom \
--partition /home/zhanya/hess-hess-0.5/fourier_ls-all.bed \
--out /external/zhanya/hess/step1
done

**Comment by lfz-123qweasd** [comment]
I have the same problem!!
